http://www.gurubee.net/oracle/sql
--system
CREATE USER SMC_USER IDENTIFIED BY SMC_USER;

--system
GRANT CREATE SESSION TO SMC_USER;
GRANT CREATE TABLE TO SMC_USER;

--SMC_USER
select 1 from dual;

--SMC_USER
CREATE TABLE A (A varchar2(10));
-- no privileges on tablespace 'SYSTEM'

--SMC_USER
CREATE TABLE A (A varchar2(10));
GRANT CREATE TABLE TO SMC_USER;
CREATE TABLESPACE smc
DATAFILE smc 
SIZE 2048M 
AUTOEXTEND ON 
NEXT 4M MAXSIZE UNLIMITED
LOGGING PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K 
SEGMENT SPACE MANAGEMENT MANUAL 
FLASHBACK ON;
--오류

--SMC_USER
CREATE TABLESPACE smc
DATAFILE 'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\smc.DBF' 
SIZE 2048M 
AUTOEXTEND ON 
NEXT 4M MAXSIZE UNLIMITED
LOGGING PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K 
SEGMENT SPACE MANAGEMENT MANUAL 
FLASHBACK ON;
--오류

--system
ALTER USER SMC_USER
IDENTIFIED BY SMC_USER
DEFAULT TABLESPACE smc;

--SMC_USER
CREATE TABLE A (A varchar2(10));
--no privileges on tablespace 'SMC'

--system
ALTER USER SMC_USER
IDENTIFIED BY SMC_USER
DEFAULT TABLESPACE smc
quota unlimited on smc;

--SMC_USER
CREATE TABLE A (A varchar2(10));
--Table created.

INSERT INTO A(A) VALUES ('ABCTEST');

select * from A;
--table 검색

DROP TABLE A;
--table 삭제

--char : ABC******
--varchar : 가변형
--ABC + 1byte

--관계형 데이터베이스
--1 : 1
--1 : N
--N : N


